### ISSUE TITLE
Scraper fails on courses with additional data in semester name

### ISSUE THREAD

**Issue by gricey432** [gricey432/uqfinal#11]
A few courses, such as https://www.uq.edu.au/study/course.html?course_code=JAPN1013 have the semester listed oddly with "(Standard)" or something else after.

Could just expand it to accept anything that starts with the correct semester name but we'd have to be sure of behaviour if it had something like theoretically 
```
Semester 1, 2017 (Standard)
Semester 1, 2017 (Secondary)
```
What would it do in this case?

**Comment by gricey432** [comment]
Also https://www.uq.edu.au/study/course.html?course_code=KORN1010
Maybe it's just a languages thing?

**Comment by jack775544** [comment]
LAWS have it too https://www.uq.edu.au/study/course.html?course_code=LAWS5206

**Comment by gricey432** [comment]
Not just a languages thing then

**Comment by gricey432** [comment]
User ran into this error, I'm just going to push a patch with the `startswith` option, if it causes other issues later I'll deal with them then.
https://www.facebook.com/uqfinal/posts/1995925117314612
