### ISSUE TITLE
"isLinear" value not correctly set in api

### ISSUE THREAD

**Issue by WilliamHayward** [gricey432/uqfinal#15]
In the [CSSE2310 api call](https://api.uqfinal.com/course/6660/CSSE2310), it has "isLinear" set to true. I'm not sure about other courses, but this is gonna make code for #2 a lot less clean.

**Comment by gricey432** [comment]
There's currently no way to detect automatically if a offering has a linear formula, so that value was previously only set to true by someone reporting it and me manually editing the database. It probably doesn't hold any significance now
