### ISSUE TITLE
[DESIGN] Internal spacing of table for items is too small

### ISSUE THREAD

**Issue by CameronAavik** [gricey432/uqfinal#20]
This is just a design issue/suggestion, but before:
![image](https://user-images.githubusercontent.com/5800980/30681063-c7a5b898-9ee6-11e7-8cde-fc29a5cb2cb5.png)
You can see in that image that the Assessment column is too close to the Weight column
And if you add a cellpadding="5" into the table, it looks like:
![image](https://user-images.githubusercontent.com/5800980/30681082-e65360f6-9ee6-11e7-8d3d-b93efffcb5b7.png)

**Comment by gricey432** [comment]
Thanks for report
