### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by ileyd** [gricey432/uqfinal#23]
I couldn't find license information anywhere for this codebase

**Comment by gricey432** [comment]
UQ Final is my copyrighted work where appropriate, there is a copyright notice to this effect in the html. The repo exists so people can see how it works and let people report bugs.

The link at the bottom of the page saying "open source" is probably incorrect, to be accurate it should just say "github" or something.

**Comment by ruchern** [comment]
I think he may be referring to the whole repository itself.

**Comment by gricey432** [comment]
Unless a licence is present in a repo granting rights to redistribute, the repository (again where appropriate) is my copyrighted work.
