### ISSUE TITLE
JS: Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by gricey432** [gricey432/uqfinal#8]
8 users have now triggered JS errors for `Invalid left-hand side in assignment`. Almost all of these have been from samsung android devices.
I had a look through the JS for any obvious causes, say `if (a = b)` instead of `===` but didn't find anything.
If anyone knows more about the error I'd appreciate some investigation into the cause and a fix.

**Comment by ruchern** [comment]
Which exact file did the error trigger in?

**Comment by gricey432** [comment]
Can't be sure, I can't reproduce it and sentry isn't recovering enough data about it to report anything.
All of them reported being on the page for several minutes (so it doesn't happen on load) but only one of them reported that a course was loaded at the time.
Error has now appeared for 24 times for 9 users.

**Comment by ruchern** [comment]
Have you tried `if (a == b)`?

**Comment by gricey432** [comment]
This seems to be a browser bug on some mobile devices. Nothing I can do.
